[lib]
proc-macro = true

[package]
name = "db-set-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_assertions = "1.4.1"
prettyplease = "0.2.25"
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = "2.0.85"
