name: Rust CI

on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
            
      - name: Build project
        run: cargo build --release

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run unit tests from root
        run: make test-unit

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
            
      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Install sqlx for makefile
        run: make setup-db-migrations

      - name: Run integration tests in `tests`
        run: make test-integration
