name: Rust CI

on: [push, pull_request]

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
            
      - name: Build project
        run: cargo build --release

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run unit tests from root
        run: cargo nextest run --release

  integration-tests:
    name: Integration tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tests
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
            
      - name: Build project
        run: cargo build --release

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run unit tests from root
        run: cargo nextest run --release

      - name: Run integration tests in `tests`
        run: 
          TOKIO_WORKER_THREADS=1 cargo nextest run -j 1 --release

