name: Rust CI

on: [push, pull_request]

jobs:


  setup:
    name: Set up and Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
            
      - name: Build project
        run: cargo build --release

      - uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run unit tests from root
        run: cargo nextest run 

      - name: Run integration tests in `tests`
        run: |
          cd tests
          TOKIO_WORKER_THREADS=1 cargo nextest run -j 1

