name: Rust CI

on: [push, pull_request]

jobs:


  setup:
    name: Set up and Cache
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5
            
      - name: Build project
        run: cargo build --release

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5

      - name: Run unit tests from root
        run: cargo test --release

  integration-tests:
    name: Run integration tests 
    runs-on: ubuntu-latest
    needs: setup
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2.7.5

      - name: Run integration tests in `tests`
        run: |
          cd tests
          cargo test --release

